{
 "title": "Wärmepumpe v2",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Uhrzeit",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  text AS metric,\n  value\nFROM calcs_grafana\nWHERE\n  metric = 'ID_WEB_AktuelleTimeStamp'\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Laufzeit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  description AS metric,\n  avg(value) AS \"value\"\nFROM history_grafana\nWHERE\n  $__timeFilter(ts) AND\n  metric = 'ID_WEB_WP_BZ_akt'\nGROUP BY 1,2\nORDER BY $__timeGroup(ts,$__interval)"
    }
   ]
  },
  {
   "title": "Wärmepumpentyp",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  value AS \"time\",\n  text AS metric,\n  value\nFROM calcvals\nWHERE\n  metric = 'ID_WEB_Code_WP_akt'\nORDER BY value"
    }
   ]
  },
  {
   "title": "Zustand",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  description AS metric,\n  avg(value) AS \"value\"\nFROM history_grafana\nWHERE\n  $__timeFilter(ts) AND\n  metric = 'ID_WEB_WP_BZ_akt'\nGROUP BY 1,2\nORDER BY $__timeGroup(ts,$__interval)"
    }
   ]
  },
  {
   "title": "Wärmepumpentyp",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  value AS \"time\",\n  text AS metric,\n  value\nFROM calcvals\nWHERE\n  metric = 'ID_WEB_Code_WP_akt_2'\nORDER BY value"
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  value AS \"time\",\n  text AS metric,\n  value\nFROM calcvals\nWHERE\n  metric = 'ID_WEB_SoftStand'\nORDER BY value"
    }
   ]
  },
  {
   "title": "Heizung",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  description AS metric,\n  avg(value) AS \"value\"\nFROM history_grafana\nWHERE\n  $__timeFilter(ts) AND\n  metric = 'ID_WEB_Temperatur_TRL_ext'\nGROUP BY 1,2\nORDER BY $__timeGroup(ts,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  description AS metric,\n  avg(value) AS \"value\"\nFROM history_grafana\nWHERE\n  $__timeFilter(ts) AND\n  metric = 'ID_WEB_Sollwert_TRL_HZ'\nGROUP BY 1,2\nORDER BY $__timeGroup(ts,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  description AS metric,\n  avg(value) AS \"value\"\nFROM history_grafana\nWHERE\n  $__timeFilter(ts) AND\n  metric = 'ID_WEB_Temperatur_TRL '\nGROUP BY 1,2\nORDER BY $__timeGroup(ts,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  description AS metric,\n  avg(value) AS \"value\"\nFROM history_grafana\nWHERE\n  $__timeFilter(ts) AND\n  metric = 'ID_WEB_Temperatur_TVL'\nGROUP BY 1,2\nORDER BY $__timeGroup(ts,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  description AS metric,\n  avg(value) AS \"value\"\nFROM history_grafana\nWHERE\n  $__timeFilter(ts) AND\n  metric = 'ID_WEB_Sollwert_TVL_MK1'\nGROUP BY 1,2\nORDER BY $__timeGroup(ts,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  description AS metric,\n  avg(value) AS \"value\"\nFROM history_grafana\nWHERE\n  $__timeFilter(ts) AND\n  metric = 'ID_WEB_Sollwert_TVL_MK1'\nGROUP BY 1,2\nORDER BY $__timeGroup(ts,$__interval)"
    }
   ]
  },
  {
   "title": "Warmwasser",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  description AS metric,\n  avg(value) AS \"value\"\nFROM history_grafana\nWHERE\n  $__timeFilter(ts) AND\n  metric = 'ID_WEB_Temperatur_TBW'\nGROUP BY 1,2\nORDER BY $__timeGroup(ts,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  description AS metric,\n  avg(value) AS \"value\"\nFROM history_grafana\nWHERE\n  $__timeFilter(ts) AND\n  metric = 'ID_WEB_Einst_BWS_akt'\nGROUP BY 1,2\nORDER BY $__timeGroup(ts,$__interval)"
    }
   ]
  },
  {
   "title": "Aussentemperatur",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  description AS metric,\n  avg(value) AS \"value\"\nFROM history_grafana\nWHERE\n  $__timeFilter(ts) AND\n  metric = 'ID_WEB_Temperatur_TA'\nGROUP BY 1,2\nORDER BY $__timeGroup(ts,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  description AS metric,\n  avg(value) AS \"value\"\nFROM history_grafana\nWHERE\n  $__timeFilter(ts) AND\n  metric = 'ID_WEB_Mitteltemperatur'\nGROUP BY 1,2\nORDER BY $__timeGroup(ts,$__interval)"
    }
   ]
  },
  {
   "title": "Durchfluss",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "litreh" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  description AS metric,\n  avg(value) AS \"value\"\nFROM history_grafana\nWHERE\n  $__timeFilter(ts) AND\n  metric = 'ID_WEB_Durchfluss_WQ'\nGROUP BY 1,2\nORDER BY $__timeGroup(ts,$__interval)"
    }
   ]
  },
  {
   "title": "Heissgas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  description AS metric,\n  avg(value) AS \"value\"\nFROM history_grafana\nWHERE\n  $__timeFilter(ts) AND\n  metric = 'ID_WEB_Temperatur_THG'\nGROUP BY 1,2\nORDER BY $__timeGroup(ts,$__interval)"
    }
   ]
  }
 ]
}